### PR TITLE
Fixed SearchLatest Mode Freeze Issue

### PR DESCRIPTION
**Pull request by l33t7here**
Fixed Issue #73.

### CODE REVIEW

**Comment by n0madic** [comment]
sorry for the delay, thanks for fixing the bug

**Comment by organicinternet** [comment]
This fix does stop the freezing, but it returns top (default) Tweets rather than latest. The Twitter front end still appears to use tweet_search_mode=live from what I can see

**Comment by organicinternet** [comment]
tweet_search_mode=live returns results with a CursorType of Top rather than Bottom, so isn't getting picked up in timeline.parseTweets

**Comment by n0madic** [comment]
any idea?

**Comment by croatiangrn** [comment]
@n0madic Try adding this for the "latest" mode in getSearchTimeline method:

q.Add("tweet_search_mode", "live")

**Pull request merged**
